name: Pack Releases

on:
  workflow_dispatch:
    inputs:
      version:
        description: 版本号 (不带v)
        required: true

jobs:
  auto-pack-releases:
    runs-on: windows-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 配置 Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: 配置 MSYS2
        uses: actions/setup-msys2@v2
        with:
          msys2-version: 'x86_64'
          install-packages: 'gcc make'

      - name: 安装依赖
        # 环境配置的依赖文件中含有打包所需依赖
        run: |
          pip install -r src\环境配置\requirements.txt
          pip list
          echo =================UPX====================
          $upx_url = (Invoke-WebRequest -Uri https://api.github.com/repos/upx/upx/releases/latest).Content | ConvertFrom-Json | Select-Object -ExpandProperty assets | Where-Object { $_.name -like "*win64.zip" } | Select-Object -ExpandProperty browser_download_url
          Write-Host "[INFO] Latest UPX download URL: $upx_url"
          Invoke-WebRequest -Uri $upx_url -OutFile "upx-latest.zip"
          7z x "upx-latest.zip" -o"."
          del "upx-latest.zip"
          tree /a /f

      - name: 复制许可文件移除Git文件
        run: |
          Copy-Item -Path "LICENSE" -Destination "src\LICENSE" -Verbose

      - name: 移除Git文件
        run: |
          Remove-Item -Path "src\Tools\【实验性工具】\定时闹钟\铃声文件\.gitkeep" -Verbose
          Remove-Item -Path "src\Tools\进制转换\进制转换（旧）.cxx" -Verbose
          Remove-Item -Path "src\Tools\WSA小工具（终止更新）" -Recurse -Verbose

      - name: 打包 C++ 文件
        run: |
          windres src\resource.rc -o src\resource.o

          # Tools\创建文件
          g++ src\Tools\创建文件\创建文件.cxx src\resource.o -o src\Tools\创建文件\创建文件.exe -finput-charset=UTF-8 -fexec-charset=UTF-8
          Remove-Item -Path "src\Tools\创建文件\创建文件.cxx" -Verbose

          # Tools\字母大小写互换
          g++ src\Tools\字母大小写互换\字母大小写互换.cxx src\resource.o -o src\Tools\字母大小写互换\字母大小写互换.exe -finput-charset=UTF-8 -fexec-charset=UTF-8
          Remove-Item -Path "src\Tools\字母大小写互换\字母大小写互换.cxx" -Verbose

          # Tools\摩斯密码
          Copy-Item -Path "D:\Duckhome\projects\MSVS\Source\Repos\Fufu_Tools\src\Tools\摩斯密码\源码\编码源码.cxx" -Destination "src\Tools\摩斯密码\编码.cxx" -Verbose
          Copy-Item -Path "D:\Duckhome\projects\MSVS\Source\Repos\Fufu_Tools\src\Tools\摩斯密码\源码\解码源码.cxx" -Destination "src\Tools\摩斯密码\解码.cxx" -Verbose
          Remove-Item -Path "src\Tools\摩斯密码\源码" -Recurse -Verbose
          g++ src\Tools\摩斯密码\编码.cxx src\resource.o -o src\Tools\摩斯密码\编码.exe -finput-charset=UTF-8 -fexec-charset=UTF-8
          g++ src\Tools\摩斯密码\解码.cxx src\resource.o -o src\Tools\摩斯密码\解码.exe -finput-charset=UTF-8 -fexec-charset=UTF-8
          Remove-Item -Path "src\Tools\摩斯密码\编码.cxx" -Verbose
          Remove-Item -Path "src\Tools\摩斯密码\解码.cxx" -Verbose

      - name: 构建 lite 版
        # 整理文件 > 压缩文件 > 清理工作目录
        env:
          PYTHONIOENCODING: utf-8
        run: |
          Copy-Item -Path "src" -Destination "Release\Fufu_Tools.v${{ github.event.inputs.version }}-lite" -Recurse -Verbose
          Remove-Item -Path "Release\Fufu_Tools.v${{ github.event.inputs.version }}-lite\芙芙工具箱(for安装程序).pyw" -Verbose
          Remove-Item -Path "Release\Fufu_Tools.v${{ github.event.inputs.version }}-lite\芙芙工具箱(for打包).pyw" -Verbose
          Remove-Item -Path "Release\Fufu_Tools.v${{ github.event.inputs.version }}-lite\Tools\【实验性工具】\hosts修改\调用(For-打包版).py" -Verbose
          Remove-Item -Path "Release\Fufu_Tools.v${{ github.event.inputs.version }}-lite\Tools\休息一下\自启动设置（For-打包版）.py" -Verbose

          # 更新版本号
          python 自动化脚本\修改版本号.py "${{ github.event.inputs.version }}" "lite" ""Release\Fufu_Tools.v${{ github.event.inputs.version }}-lite"

          # 压缩为 zip
          7z a -tzip "Release\Fufu_Tools.v${{ github.event.inputs.version }}-lite.zip" "Release\Fufu_Tools.v${{ github.event.inputs.version }}-lite\*"
          # 压缩为 7z
          7z a -t7z "Release\Fufu_Tools.v${{ github.event.inputs.version }}-lite.7z" "Release\Fufu_Tools.v${{ github.event.inputs.version }}-lite\*"
          # 清理工作目录
          Remove-Item -Path "Release\Fufu_Tools.v${{ github.event.inputs.version }}-lite" -Recurse -Verbose

      - name: 构建 pack 版
        env:
          PYTHONIOENCODING: utf-8
        run: |
          Copy-Item -Path "src" -Destination "Release\Fufu_Tools.v${{ github.event.inputs.version }}" -Recurse -Verbose
          Remove-Item -Path "Release\Fufu_Tools.v${{ github.event.inputs.version }}\芙芙工具箱(for安装程序).pyw" -Verbose
          Remove-Item -Path "Release\Fufu_Tools.v${{ github.event.inputs.version }}\芙芙工具箱.pyw" -Verbose
          Rename-Item -Path "Release\Fufu_Tools.v${{ github.event.inputs.version }}\芙芙工具箱(for打包).pyw" -NewName "芙芙工具箱.pyw" -Verbose
          Remove-Item -Path "Release\Fufu_Tools.v${{ github.event.inputs.version }}\Tools\【实验性工具】\hosts修改\调用.py" -Verbose
          Rename-Item -Path "Release\Fufu_Tools.v${{ github.event.inputs.version }}\Tools\【实验性工具】\hosts修改\调用(For-打包版).py" -NewName "调用.py" -Verbose
          Remove-Item -Path "Release\Fufu_Tools.v${{ github.event.inputs.version }}\Tools\休息一下\自启动设置.py" -Verbose
          Rename-Item -Path "Release\Fufu_Tools.v${{ github.event.inputs.version }}\Tools\休息一下\自启动设置（For-打包版）.py" -NewName "自启动设置.py" -Verbose

          # 更新版本号
          python 自动化脚本\修改版本号.py "${{ github.event.inputs.version }}" "pack" ""Release\Fufu_Tools.v${{ github.event.inputs.version }}"

          python DEV-PACK.py "Release\Fufu_Tools.v${{ github.event.inputs.version }}" "src\ico.ico" "Release\logs\pack" -s

          # 压缩为 zip
          7z a -tzip "Release\Fufu_Tools.v${{ github.event.inputs.version }}.zip" "Release\Fufu_Tools.v${{ github.event.inputs.version }}\*"
          # 压缩为 7z
          7z a -t7z "Release\Fufu_Tools.v${{ github.event.inputs.version }}.7z" "Release\Fufu_Tools.v${{ github.event.inputs.version }}\*"
          # 压缩为 7z - 压缩等级 9 - 极限压缩
          7z a -t7z -mx9 "Release\Fufu_Tools.v${{ github.event.inputs.version }}-Extreme_compression.7z" "Release\Fufu_Tools.v${{ github.event.inputs.version }}\*"
          # 清理工作目录
          Remove-Item -Path "Release\Fufu_Tools.v${{ github.event.inputs.version }}" -Recurse -Verbose

      - name: 构建安装程序版 (exe)
        env:
          PYTHONIOENCODING: utf-8
        run: |
          Copy-Item -Path "src" -Destination "Release\Fufu_Tools.v${{ github.event.inputs.version }}-exe" -Recurse -Verbose
          Remove-Item -Path "Release\Fufu_Tools.v${{ github.event.inputs.version }}-exe\芙芙工具箱.pyw" -Verbose
          Remove-Item -Path "Release\Fufu_Tools.v${{ github.event.inputs.version }}-exe\芙芙工具箱(for打包).pyw" -Verbose
          Rename-Item -Path "Release\Fufu_Tools.v${{ github.event.inputs.version }}-exe\芙芙工具箱(for安装程序).pyw" -NewName "芙芙工具箱.pyw" -Verbose
          Remove-Item -Path "Release\Fufu_Tools.v${{ github.event.inputs.version }}-exe\Tools\【实验性工具】\hosts修改\调用.py" -Verbose
          Rename-Item -Path "Release\Fufu_Tools.v${{ github.event.inputs.version }}-exe\Tools\【实验性工具】\hosts修改\调用(For-打包版).py" -NewName "调用.py" -Verbose
          Remove-Item -Path "Release\Fufu_Tools.v${{ github.event.inputs.version }}-exe\Tools\休息一下\自启动设置.py" -Verbose
          Rename-Item -Path "Release\Fufu_Tools.v${{ github.event.inputs.version }}-exe\Tools\休息一下\自启动设置（For-打包版）.py" -NewName "自启动设置.py" -Verbose

          # 更新版本号
          python 自动化脚本\修改版本号.py "${{ github.event.inputs.version }}" "exe" ""Release\Fufu_Tools.v${{ github.event.inputs.version }}-exe"

          python DEV-PACK.py "Release\Fufu_Tools.v${{ github.event.inputs.version }}-exe" "src\ico.ico" "Release\logs\exe" -s

      - name: 上传构建文件
        uses: actions/upload-artifact@v4
        with:
          name: 构建文件
          path: Release\**
